### ISSUE TITLE
Could not find browser revision

### ISSUE THREAD

**Issue by DevAmiyo** [mlg404/whatsapp-music-bot#19]
~[[22:30:38.766]] [ERROR] Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (E:\Github\Amiyos-WhatsApp_MusicBot\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:79:23)
    at Client.initialize (E:\Github\Amiyos-WhatsApp_MusicBot\node_modules\whatsapp-web.js\src\Client.js:67:25)
[ERROR] 22:30:38 Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.~

**Comment by DevAmiyo** [comment]
@mlg404 Help ?
