### ISSUE TITLE
ReferenceError: webpackChunkbuild is not defined

### ISSUE THREAD

**Issue by DevAmiyo** [mlg404/whatsapp-music-bot#23]
`[[20:48:13.807]] [ERROR] Error: Evaluation failed: ReferenceError: webpackChunkbuild is not defined
    at fillModuleArray (eval at <anonymous> (:2:5), <anonymous>:6:5)
    at moduleRaid (eval at <anonymous> (:2:5), <anonymous>:15:3)
    at __puppeteer_evaluation_script__:4:17
    at ExecutionContext._evaluateInternal (E:\music\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExecutionContext.evaluate (E:\music\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at Client.initialize (E:\music\node_modules\whatsapp-web.js\src\Client.js:148:9)
[ERROR] 20:48:13 Error: Evaluation failed: ReferenceError: webpackChunkbuild is not defined
    at fillModuleArray (eval at <anonymous> (:2:5), <anonymous>:6:5)
    at moduleRaid (eval at <anonymous> (:2:5), <anonymous>:15:3)
    at __puppeteer_evaluation_script__:4:17`

**Comment by mlg404** [comment]
We are working on a new version correcting bugs. 
I will ask u to just wait until there
ETA: next week
