### ISSUE TITLE
Cannot read properties of undefined (reading 'Sticker')

### ISSUE THREAD

**Issue by DevAmiyo** [mlg404/whatsapp-music-bot#30]
```console
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Sticker')
    at __puppeteer_evaluation_script__:32:70
    at ExecutionContext._evaluateInternal (E:\Github\Personal\WhatsAppMusic\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExecutionContext.evaluate (E:\Github\Personal\WhatsAppMusic\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
    at Client.initialize (E:\Github\Personal\WhatsAppMusic\node_modules\whatsapp-web.js\src\Client.js:187:9)
[ERROR] 09:36:52 Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Sticker')
    at __puppeteer_evaluation_script__:32:70
```

**Comment by mehulpuri** [comment]
same issue

**Comment by DevAmiyo** [comment]
@mehulpuri Run this in terminal
```
$ yarn upgrade --latest
```

**Comment by mehulpuri** [comment]
thanks worked for me
