### ISSUE TITLE
HELP ME!

### ISSUE THREAD

**Issue by ben-dev2609** [mlg404/whatsapp-music-bot#5]
[Uploading Screenshot (28).png…]()

help

**Comment by mlg404** [comment]
i can't see the image

what happened?

**Comment by ben-dev2609** [comment]
![Uploading Screenshot (28).png…]()

**Comment by ben-dev2609** [comment]
> i can't see the image
> 
> what happened?

npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-09-22T13_46_35_529Z-debug.log

C:\Users\User\whatsapp-music-bot>npm i
npm WARN teste_wpp@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 22.182s

14 packages are looking for funding
  run `npm fund` for details
![Uploading Screenshot (28).png…]()

**Comment by mlg404** [comment]
> No repository field

Now, try run thhis following command:
```npm run dev```

**Comment by ben-dev2609** [comment]
why if i say command !play the answer "nao encontrado,tente novamente"


can you make this to english?

**Comment by ben-dev2609** [comment]
answer pls

**Comment by mlg404** [comment]
Try uninstall yt-search and install it again

**Comment by ben-dev2609** [comment]
can you screenshoot ? i cant make uninstalll

**Comment by ben-dev2609** [comment]
(node:15860) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "canvas" failed: timeout 45000ms exceeded
    at new WaitTask (C:\Users\User\whatsapp-music-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:394:34)
    at DOMWorld._waitForSelectorOrXPath (C:\Users\User\whatsapp-music-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:326:26)
    at DOMWorld.waitForSelector (C:\Users\User\whatsapp-music-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:309:21)
    at Frame.waitForSelector (C:\Users\User\whatsapp-music-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:830:51)
    at Page.waitForSelector (C:\Users\User\whatsapp-music-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1289:33)
    at Timeout.getQrCode (C:\Users\User\whatsapp-music-bot\node_modules\whatsapp-web.js\src\Client.js:125:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on DownloadYTAudio instance at:
    at FfmpegCommand.<anonymous> (C:\Users\User\whatsapp-music-bot\node_modules\yt-dl-playlist\lib\download-audio.js:82:14)
    at FfmpegCommand.emit (events.js:315:20)
    at emitEnd (C:\Users\User\whatsapp-music-bot\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at C:\Users\User\whatsapp-music-bot\node_modules\fluent-ffmpeg\lib\processor.js:433:16
    at wrapper (C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:268:20)
    at next (C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:4582:24)
    at C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:321:20
    at wrapper (C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:268:20)
    at next (C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:4582:24)
    at C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:321:20 {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /usr/bin/ffmpeg',
  path: '/usr/bin/ffmpeg',
  spawnargs: [ '-formats' ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by mlg404** [comment]
Did you install ffmpeg?
Did u set up ffmpeg?

**Comment by ben-dev2609** [comment]
hmm no how? at nodejs?

**Comment by mlg404** [comment]
See https://ffmpeg.org/

**Comment by ben-dev2609** [comment]
if i see what more?

**Comment by ben-dev2609** [comment]
learn me or make tutorial at youtube PLEASE

**Comment by mlg404** [comment]
Did u install it? You need ffmpeg to do the conversions

**Comment by ben-dev2609** [comment]
i install it

**Comment by ben-dev2609** [comment]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on DownloadYTAudio instance at:
    at FfmpegCommand.<anonymous> (C:\Users\User\whatsapp-music-bot\node_modules\yt-dl-playlist\lib\download-audio.js:82:14)
    at FfmpegCommand.emit (events.js:315:20)
    at emitEnd (C:\Users\User\whatsapp-music-bot\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at C:\Users\User\whatsapp-music-bot\node_modules\fluent-ffmpeg\lib\processor.js:433:16
    at wrapper (C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:268:20)
    at next (C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:4582:24)
    at C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:321:20
    at wrapper (C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:268:20)
    at next (C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:4582:24)
    at C:\Users\User\whatsapp-music-bot\node_modules\async\dist\async.js:321:20 {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /usr/bin/ffmpeg',
  path: '/usr/bin/ffmpeg',
  spawnargs: [ '-formats' ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by mlg404** [comment]
You need to change this line `path: '/usr/bin/ffmpeg',` to your ffmpeg path. The path i upload was a ubuntu default path

**Comment by Akarisu212** [comment]
How to change the patch ffmpeg pls teach me

**Comment by Akarisu212** [comment]
![Tak berjudul86_20201027170046](https://user-images.githubusercontent.com/73526026/97286426-0ee49100-1876-11eb-96e5-e07e9eae79e7.png)
Pls

**Comment by ben-dev2609** [comment]
still cant

**Comment by fasterbrain** [comment]
Hi bro
Please I'm stuck here bro, i was hoping you could help me or recommend me a youtube video on how's done.
![error](https://user-images.githubusercontent.com/32088728/98440149-dd589a80-20ab-11eb-9fd9-29e1a74a0caf.PNG)
May Allah (swt) bless you.

**Comment by dhruvgp180901** [comment]
> ![Tak berjudul86_20201027170046](https://user-images.githubusercontent.com/73526026/97286426-0ee49100-1876-11eb-96e5-e07e9eae79e7.png)
> Pls

This error occurs because the extractor couldn't extract the browser zip-file properly, so for this, you should go to **node_modules/puppeteer** folder, there you'll find a ZIP file extract it to a folder in beside that ZIP file whose name starts with linux.
And then run `yarn install` again, you're good to go then.

**Comment by AnonySharma** [comment]
> ![Tak berjudul86_20201027170046](https://user-images.githubusercontent.com/73526026/97286426-0ee49100-1876-11eb-96e5-e07e9eae79e7.png)
> Pls

This error occurs because the extractor couldn't extract the browser zip-file properly, so for this, you should go to **node_modules/puppeteer** folder, there you'll find a ZIP file extract it to a folder in beside that ZIP file whose name starts with linux.
And then run `yarn install` again, you're good to go then.
