### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by oliveripkanam** [mlg404/whatsapp-music-bot#6]
everytime i try to play a song it says " app crashed - waiting for file changes before starting..."

can u help? thx

**Comment by mlg404** [comment]
Give more details. Show the entire error log

**Comment by oliveripkanam** [comment]
now it shows this:

(node:2342) UnhandledPromiseRejectionWarning: Error: Could not find player config
    at exports.getBasicInfo (/Users/oli/whatsapp-music-bot/node_modules/ytdl-core/lib/info.js:59:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.<computed> [as getBasicInfo] (/Users/oli/whatsapp-music-bot/node_modules/ytdl-core/lib/info.js:296:18)
    at async exports.getFullInfo (/Users/oli/whatsapp-music-bot/node_modules/ytdl-core/lib/info.js:187:14)
    at async Object.exports.<computed> [as getFullInfo] (/Users/oli/whatsapp-music-bot/node_modules/ytdl-core/lib/info.js:296:18)
(node:2342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
